#docker compose with 3 services: mariadb, NGINX, wordpress
version: "3"
networks:
  inception_network:
services:
  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    env_file: .env
    build:
      context: ./requirements/wordpress
    ports:
      - '9000:9000'
    volumes:
      - wordpress_vol:/var/www/html
    container_name: wordpress
    restart: always
  nginx:
    image: nginx
    networks:
      - inception_network
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    ports:
      - '443:443'
    volumes:
      - wordpress_vol:/var/www/html
    container_name: nginx
    restart: always
  mariadb:
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        - WP_DB_NAME=${WP_DB_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - mariadb_vol:/var/lib/mysql/
    networks:
      - inception_network
    restart: always
volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/alevra/data/wordpress'
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/alevra/data/mariadb'